server:
  port: 9881

spring:
  datasource:
    hikari:
      pool-name: SYW_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
      jdbc-url: jdbc:mysql://47.102.152.243:3306/syw_jdbc_demo
      username: root
      password: Dv8,zia13vvKqdly
      driver-class-name: com.mysql.cj.jdbc.Driver

school:
  service:
    enabled: true